behaviors:
  #name of brain we want to train
  HitBall: 
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 6e-6 #3.0e-4
      beta: 5.0e-4
      epsilon: 0.1 #0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false #previously false, should be true?
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000 #previously 500,000
    time_horizon: 64
    summary_freq: 10000